### ISSUE TITLE
sh: 1: set: Illegal option -o pipefail error in "irap_gtf_to_fasta". 

### ISSUE THREAD

**Issue by shrho** [nunofonseca/irap#77]
irap_gtf_to_fasta -g /home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.gtf --genome /home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485
.EcoliK12AG100.dna.chromosome.I.fa --types 'protein_coding|IG_([a-zA-Z0-9]+)_gene|TR_([a-zA-Z0-9]+)_gene' --out /home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.
tmp && mv /home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.tmp /home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.Ecoli
K12AG100.90.trans.irap.fa
gtf=/home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.gtf
fasta=/home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.dna.chromosome.I.fa
types=protein_coding|IG_([a-zA-Z0-9]+)_gene|TR_([a-zA-Z0-9]+)_gene
out=/home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.tmp
Creating temporary gtf...
Creating temporary gtf...done.
Loading temporary GTF...
Transcripts loaded:4003
done.
Creating fasta (1/2)...
sh: 1: set: Illegal option -o pipefail
set -o pipefail; tophat2_gtf_to_fasta /home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa.tmp.tmp.gtf /home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Esche
richia_coli_k_12_gca_000981485.EcoliK12AG100.dna.chromosome.I.fa /dev/stdout|tail -n +2| sed -E  's/^>([a-zA-Z0-9|]+)\s/>/;s/\s.*//' > /home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12
AG100.90.trans.irap.fa.tmp.tmp1 failed: 512/home/mc_shrho/src/irap_install/scripts/../aux/mk/irap_core.mk:2078: recipe for target '/home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG10
0.90.trans.irap.fa' failed
make: *** [/home/mc_shrho/src/irap_install/data/reference/ecoli_k12/Escherichia_coli_k_12_gca_000981485.EcoliK12AG100.90.trans.irap.fa] Error 1

**Comment by nunofonseca** [comment]
Hi,

I'm unable to replicate the problem. From the pasted message it seems that you are using a shell different from bash while running iRAP.
 
Setting the shell to be bash initially should solve the issue. This can be achieved by starting to run bash first in the terminal before setting iRAP's environment variables:
`bash`
`source path_to_irap_setup.sh_file`

and then rerun irap (on the same terminal). Please let me know if the solution works or not.
Cheers.

**Comment by shrho** [comment]
Hi,

It is odd because I am running bash but still getting this issue.
I also thought this was the issue with BASH.
It seems that the code resides in a python script. I tried to put bash in
"system ("set -o pipefail ......") command and the code was executed but a
new instance of bash is executed. I just removed "-o pipefail" and the
entire irap scripts runs without errors.

Best,
Seong Hwan

**Comment by nunofonseca** [comment]
Hi,
It is indeed strange. I wonder if it may be an issue with the version of bash - pipefail was introduced in version 3,  if the version that you are using is older than 3 then it would explain the problem. (you can find out the version  by running `bash --version`).
Cheers.
